package au.edu.unsw.sltf.currency;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-03T11:38:19.019+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://sltf.unsw.edu.au/currency", name = "CurrencyConvertServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CurrencyConvertServicePortType {

    @WebResult(name = "exchangeRateResponseMsg", targetNamespace = "http://sltf.unsw.edu.au/currency", partName = "parameters")
    @Action(input = "urn:exchangeRateRequestMsg", output = "urn:exchangeRateResponseMsg", fault = {@FaultAction(className = CurrencyConvertFaultException.class, value = "http://sltf.unsw.edu.au/currency/CurrencyConvertServicePortType/yahooExchangeRate/Fault/CurrencyConvertFault_Exception")})
    @WebMethod(action = "urn:exchangeRateRequestMsg")
    public ExchangeRateResponseMsg yahooExchangeRate(
        @WebParam(partName = "parameters", name = "exchangeRateRequestMsg", targetNamespace = "http://sltf.unsw.edu.au/currency")
        ExchangeRateRequestMsg parameters
    ) throws CurrencyConvertFaultException;
}
