package au.edu.unsw.sltf.currency;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-03T11:38:19.021+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "CurrencyConvertServicePortTypeImplService", 
                  wsdlLocation = "http://localhost:8080/9322ass1/currencyConvertService?wsdl",
                  targetNamespace = "http://currency.sltf.unsw.edu.au/") 
public class CurrencyConvertServicePortTypeImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://currency.sltf.unsw.edu.au/", "CurrencyConvertServicePortTypeImplService");
    public final static QName CurrencyConvertServicePortTypeImplPort = new QName("http://currency.sltf.unsw.edu.au/", "CurrencyConvertServicePortTypeImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/9322ass1/currencyConvertService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CurrencyConvertServicePortTypeImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/9322ass1/currencyConvertService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CurrencyConvertServicePortTypeImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CurrencyConvertServicePortTypeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyConvertServicePortTypeImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CurrencyConvertServicePortTypeImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CurrencyConvertServicePortTypeImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CurrencyConvertServicePortTypeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CurrencyConvertServicePortType
     */
    @WebEndpoint(name = "CurrencyConvertServicePortTypeImplPort")
    public CurrencyConvertServicePortType getCurrencyConvertServicePortTypeImplPort() {
        return super.getPort(CurrencyConvertServicePortTypeImplPort, CurrencyConvertServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrencyConvertServicePortType
     */
    @WebEndpoint(name = "CurrencyConvertServicePortTypeImplPort")
    public CurrencyConvertServicePortType getCurrencyConvertServicePortTypeImplPort(WebServiceFeature... features) {
        return super.getPort(CurrencyConvertServicePortTypeImplPort, CurrencyConvertServicePortType.class, features);
    }

}
