package au.edu.unsw.sltf.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-02T20:04:58.065+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "ImportDownloadServicesPortTypeImplService", 
                  wsdlLocation = "http://localhost:8080/9322ass1/importDownloadService?wsdl",
                  targetNamespace = "http://services.sltf.unsw.edu.au/") 
public class ImportDownloadServicesPortTypeImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.sltf.unsw.edu.au/", "ImportDownloadServicesPortTypeImplService");
    public final static QName ImportDownloadServicesPortTypeImplPort = new QName("http://services.sltf.unsw.edu.au/", "ImportDownloadServicesPortTypeImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/9322ass1/importDownloadService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ImportDownloadServicesPortTypeImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/9322ass1/importDownloadService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ImportDownloadServicesPortTypeImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ImportDownloadServicesPortTypeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImportDownloadServicesPortTypeImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ImportDownloadServicesPortTypeImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ImportDownloadServicesPortTypeImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ImportDownloadServicesPortTypeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ImportDownloadServicesPortType
     */
    @WebEndpoint(name = "ImportDownloadServicesPortTypeImplPort")
    public ImportDownloadServicesPortType getImportDownloadServicesPortTypeImplPort() {
        return super.getPort(ImportDownloadServicesPortTypeImplPort, ImportDownloadServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImportDownloadServicesPortType
     */
    @WebEndpoint(name = "ImportDownloadServicesPortTypeImplPort")
    public ImportDownloadServicesPortType getImportDownloadServicesPortTypeImplPort(WebServiceFeature... features) {
        return super.getPort(ImportDownloadServicesPortTypeImplPort, ImportDownloadServicesPortType.class, features);
    }

}
