package au.edu.unsw.sltf.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-03T11:35:41.694+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://sltf.unsw.edu.au/services", name = "ImportDownloadServicesPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ImportDownloadServicesPortType {

    @WebResult(name = "dataURL", targetNamespace = "http://sltf.unsw.edu.au/services")
    @Action(input = "urn:downloadFile", output = "urn:downloadFileResponse", fault = {@FaultAction(className = ImportDownloadFaultException.class, value = "http://sltf.unsw.edu.au/services/ImportDownloadServicesPortType/downloadFile/Fault/ImportDownloadFault_Exception")})
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://sltf.unsw.edu.au/services", className = "au.edu.unsw.sltf.services.DownloadFile")
    @WebMethod(action = "urn:downloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://sltf.unsw.edu.au/services", className = "au.edu.unsw.sltf.services.DownloadFileResponse")
    public java.lang.String downloadFile(
        @WebParam(name = "eventSetId", targetNamespace = "http://sltf.unsw.edu.au/services")
        java.lang.String eventSetId,
        @WebParam(name = "fileType", targetNamespace = "http://sltf.unsw.edu.au/services")
        java.lang.String fileType
    ) throws ImportDownloadFaultException;

    @WebResult(name = "eventSetId", targetNamespace = "http://sltf.unsw.edu.au/services")
    @Action(input = "urn:importMarketData", output = "urn:importMarketDataResponse", fault = {@FaultAction(className = ImportDownloadFaultException.class, value = "http://sltf.unsw.edu.au/services/ImportDownloadServicesPortType/importMarketData/Fault/ImportDownloadFault_Exception")})
    @RequestWrapper(localName = "importMarketData", targetNamespace = "http://sltf.unsw.edu.au/services", className = "au.edu.unsw.sltf.services.ImportMarketData")
    @WebMethod(action = "urn:importMarketData")
    @ResponseWrapper(localName = "importMarketDataResponse", targetNamespace = "http://sltf.unsw.edu.au/services", className = "au.edu.unsw.sltf.services.ImportMarketDataResponse")
    public java.lang.String importMarketData(
        @WebParam(name = "sec", targetNamespace = "http://sltf.unsw.edu.au/services")
        java.lang.String sec,
        @WebParam(name = "startDate", targetNamespace = "http://sltf.unsw.edu.au/services")
        java.lang.String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://sltf.unsw.edu.au/services")
        java.lang.String endDate,
        @WebParam(name = "dataSourceURL", targetNamespace = "http://sltf.unsw.edu.au/services")
        java.lang.String dataSourceURL
    ) throws ImportDownloadFaultException;
}
