package au.edu.unsw.sltf.marketdatautil;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-05T15:40:52.213+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://sltf.unsw.edu.au/marketdatautil", name = "MarketDataUtilServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MarketDataUtilServicePortType {

    @WebResult(name = "convertMarketDataResponseMsg", targetNamespace = "http://sltf.unsw.edu.au/marketdatautil", partName = "parameters")
    @Action(input = "urn:convertMarketDataRequestMsg", output = "urn:convertMarketDataResponseMsg", fault = {})
    @WebMethod(action = "urn:convertMarketDataRequestMsg")
    public ConvertMarketDataResponseMsg convertMarketData(
        @WebParam(partName = "parameters", name = "convertMarketDataRequestMsg", targetNamespace = "http://sltf.unsw.edu.au/marketdatautil")
        ConvertMarketDataRequestMsg parameters
    ) throws MarketDataUtilFaultMsg_Exception;

    @WebResult(name = "summaryMarketDataResponseMsg", targetNamespace = "http://sltf.unsw.edu.au/marketdatautil", partName = "parameters")
    @Action(input = "urn:summaryMarketDataRequestMsg", output = "urn:summaryMarketDataResponseMsg", fault = {})
    @WebMethod(action = "urn:summaryMarketDataRequestMsg")
    public SummaryMarketDataResponseMsg summaryMarketData(
        @WebParam(partName = "parameters", name = "summaryMarketDataRequestMsg", targetNamespace = "http://sltf.unsw.edu.au/marketdatautil")
        SummaryMarketDataRequestMsg parameters
    ) throws MarketDataUtilFaultMsg_Exception;
}
