
package au.edu.unsw.sltf.marketdatautil;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-05T15:40:52.208+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "MarketDataUtilFaultMsg", targetNamespace = "http://sltf.unsw.edu.au/marketdatautil")
public class MarketDataUtilFaultMsg_Exception extends Exception {
    
    private au.edu.unsw.sltf.marketdatautil.MarketDataUtilFaultMsg marketDataUtilFaultMsg;

    public MarketDataUtilFaultMsg_Exception() {
        super();
    }
    
    public MarketDataUtilFaultMsg_Exception(String message) {
        super(message);
    }
    
    public MarketDataUtilFaultMsg_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MarketDataUtilFaultMsg_Exception(String message, au.edu.unsw.sltf.marketdatautil.MarketDataUtilFaultMsg marketDataUtilFaultMsg) {
        super(message);
        this.marketDataUtilFaultMsg = marketDataUtilFaultMsg;
    }

    public MarketDataUtilFaultMsg_Exception(String message, au.edu.unsw.sltf.marketdatautil.MarketDataUtilFaultMsg marketDataUtilFaultMsg, Throwable cause) {
        super(message, cause);
        this.marketDataUtilFaultMsg = marketDataUtilFaultMsg;
    }

    public au.edu.unsw.sltf.marketdatautil.MarketDataUtilFaultMsg getFaultInfo() {
        return this.marketDataUtilFaultMsg;
    }
}
