
package au.edu.unsw.sltf.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-05T15:40:52.089+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "importDownloadFault", targetNamespace = "http://sltf.unsw.edu.au/services")
public class ImportDownloadFault_Exception extends Exception {
    
    private au.edu.unsw.sltf.services.ImportDownloadFault importDownloadFault;

    public ImportDownloadFault_Exception() {
        super();
    }
    
    public ImportDownloadFault_Exception(String message) {
        super(message);
    }
    
    public ImportDownloadFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ImportDownloadFault_Exception(String message, au.edu.unsw.sltf.services.ImportDownloadFault importDownloadFault) {
        super(message);
        this.importDownloadFault = importDownloadFault;
    }

    public ImportDownloadFault_Exception(String message, au.edu.unsw.sltf.services.ImportDownloadFault importDownloadFault, Throwable cause) {
        super(message, cause);
        this.importDownloadFault = importDownloadFault;
    }

    public au.edu.unsw.sltf.services.ImportDownloadFault getFaultInfo() {
        return this.importDownloadFault;
    }
}
