
package au.edu.unsw.sltf.marketdatautil;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-04T14:37:19.382+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "MarketDataUtilFaultMsg", targetNamespace = "http://sltf.unsw.edu.au/marketdatautil")
public class MarketDataUtilFaultMsgException extends Exception {
    
    private au.edu.unsw.sltf.marketdatautil.MarketDataUtilFaultMsg marketDataUtilFaultMsg;

    public MarketDataUtilFaultMsgException() {
        super();
    }
    
    public MarketDataUtilFaultMsgException(String message) {
        super(message);
    }
    
    public MarketDataUtilFaultMsgException(String message, Throwable cause) {
        super(message, cause);
    }

    public MarketDataUtilFaultMsgException(String message, au.edu.unsw.sltf.marketdatautil.MarketDataUtilFaultMsg marketDataUtilFaultMsg) {
        super(message);
        this.marketDataUtilFaultMsg = marketDataUtilFaultMsg;
    }

    public MarketDataUtilFaultMsgException(String message, au.edu.unsw.sltf.marketdatautil.MarketDataUtilFaultMsg marketDataUtilFaultMsg, Throwable cause) {
        super(message, cause);
        this.marketDataUtilFaultMsg = marketDataUtilFaultMsg;
    }

    public au.edu.unsw.sltf.marketdatautil.MarketDataUtilFaultMsg getFaultInfo() {
        return this.marketDataUtilFaultMsg;
    }
}
